### ISSUE TITLE
audit teacher resources files

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#414]
**DATA SCIENCE**
- [x] @ds26gte waiting on feedback on fall 2021 branch `pathways/data-science/.../resources/about-datasets/for-teachers-about-datasets.adoc` See comment at end of document
- [x] animals dataset links are out of date
- [x] are you still encouraging folks to checkout the pudding?
- [x] definitely add links to desmos library (data science)
- [x] make new about dataset file and link it here

**Overarching questions that apply to all pathways:**
- [x] Does the broadening participation slide deck really address what you want it to? Guessing this needs updating? I don't really understand who it's written for or why it's in a slide deck format
- [x] @ds26gte the `exercises_and_solutions` generation needs to be updated, to include anything in `*-printable-exercise`. Please check off this box once it's completed.
- [x] Exercises & solutions needs CSS fixing from Emmanuel

**ALGEBRA**
- [x] make asciidoc of assessment guidance to web 
- [x] make asciidoc of DR rubric
- [x] What is the story with this [Buggy Design Recipe folder?! ](https://www.bootstrapworld.org/materials/spring2021/en-us/courses/algebra-wescheme/resources/BuggyRecipes/pages/)
- [x] Is this all still true? If so, surprised I didn't hear it hyped in every single workshop last summer...
> Research
> As a member of the Bootstrap Community, we invite you and your class to join our research effort!
> You’ll help us investigate the effectiveness of our curriculum, which helps us improve our existing materials and pedagogy for both students and teachers.
> 
> In exchange for participation, you’ll receive a choice of a $50 Amazon gift card or up to 50 FREE student workbooks.
> We are in particular need of data from control classes that have not used Bootstrap. If you are able to gather data in a similar class to your Bootstrap class, we can offer an additional $50 gift card or set of 50 workbooks.
> 
> Participation is easy: Just fill out this Google Form and you’ll receive everything you need. We handle all the grading!
> 
> You can also help us evaluate how students react to having built a game by having them fill out this brief (10 minute) anonymous survey.
> We frequently get questions about various aspects of the game project, such as creativity and appeal to students. Your input helps us assess and answer these questions. (No compensation for the online survey, but you’re awesome in our book!)

- [x] We should definitely have direct links to the Desmos activity collections here (algebra, pyret and wescheme)
- [x] Links to Starter Files should include the full list of starter files!
- [x] other links section doesn't make sense - 2 of the files are for giving feedback to Bootstrap (are they up-to-date?). one of the files is a template for use with students. we should disaggregate these.
- [x] I'd like to add a set of starter files for completed flags / coding practice exercise so that teachers have more examples of complex code at their fingertips.

**Comment by flannery-denny** [comment]
perhaps we want extra practice for order of operations in here instead of in the lesson plan?

**Comment by flannery-denny** [comment]
@schanzer I'd like to reorganize these pages - do you want to discuss before I do? Or should I give it a shot and let you weigh in?

**Comment by schanzer** [comment]
@ds26gte the `exercises_and_solutions` generation needs to be updated, to include anything in `*-printable-exercise`.

**Comment by flannery-denny** [comment]
@schanzer 

- [ ] lmk if you like the way the algebra wescheme starter files look now. If that works for you I'll update the pyret links.
- [ ] Is there a way to move the PD workbook link to the Workshop section?

**Comment by ds26gte** [comment]
exercises_and_solutions fix pushed to fall2021.

**Comment by flannery-denny** [comment]
@schanzer when you get a chance please look at the two new asciidoc files in `algebra/resources/pages/assessment-guidance` and `dr-rubric`and lmk if the formatting is good enough... and if not, what other strategies you'd suggest employing.

**Comment by flannery-denny** [comment]
@ds26gte Two questions re fall branch `pathways/data-science/.../resources/about-datasets/for-teachers-about-datasets.adoc`
-In the html version some of the fragments include the bootstrap signature. I don't want any of them to include that. How do I change that?
-In the pdf version, the MLB Hitting Stats (2018) Header bar only goes across about 60% of the page. How do I fix that?

**Comment by flannery-denny** [comment]
@schanzer @ds26gte I heard that the comment above had been addressed but I still can't build the `for-teachers-about-datasets.adoc` file correctly. Can you?

**Comment by schanzer** [comment]
Confirmed fixed. Does that mean the last item in this issue is just the final check box?￼
