### ISSUE TITLE
Collecting data / data cleaning

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#793]
- [x] Draft of lesson and workbooks
- [x] Do we need a starter file? (leaning no...)
- [ ] Project: survey design and collection

**Comment by flannery-denny** [comment]
@schanzer You're right. This lesson was pretty close!
I am planning to:

- [ ] add a starterfile for them to engage with before they look at the google sheet, so they can see the impact of typos in a pie chart, etc.
- [ ] adjust the **New Animals** google sheet so that it also has some spelling / capitalization discrepancies
- [ ] adjust the **Height v Age** Survey so that it is obviously missing some important categories as response choices for the what grade are you in question
- [ ] make a workbook page to expand upon the synthesize questions
- [x] add a link to [this article](https://www.nytimes.com/2017/05/10/opinion/the-census-wont-collect-lgbt-data-thats-a-problem.html)
- [ ] I might look for another article about how the nyclu forced the nypd to start collecting stop n frisk data

**Comment by schanzer** [comment]
Looks great, @flannery-denny . The one thing I'd push back on is having them use a starter file _before_ looking at the google sheet. Starting with the sheet requires them to look at a lot more closely at the data, whereas the starter file allows them to just click run and report on the first error they see. And since they'll _all_ get the same first error, this also nullifies the benefits of collaboration and crowdsourcing.

(It make also risk of giving them the misconception that "pyret will find all my problems", which is the opposite of what we want them to take away)

**Comment by flannery-denny** [comment]
@schanzer
The starter file I want to engage them with at the beginning will not have any error messages. It will be of a different dataset than the google file.

Flannery

**Comment by flannery-denny** [comment]
@schanzer I've pushed a draft of the lesson and pages:

- [ ] I'd like some css magic on `survey-analysis.adoc` to add space between the last fitb and the next question.
- [ ] I know we still have to make a rubric for the project

Curious to hear your other thoughts. Will dig back into it tomorrow.

**Comment by schanzer** [comment]
@flannery-denny looks like you've taken it all the way! I love the worksheet you've created. I think this is _super_ close. Unfortunately I don't see a `survey-analysis.adoc` file in the lesson folder. Is it possible you forgot to check in the file?

**Comment by flannery-denny** [comment]
yep. apparently my entire commit got blocked by not having pulled and I didn't notice... sorry. Now you can see the lesson as intended, which, hopefully, only looks better than what you've already seen!

**Comment by flannery-denny** [comment]
@schanzer yep. apparently my entire commit got blocked by not having pulled and I didn't notice... sorry. Now you can see the lesson as intended, which, hopefully, only looks better than what you've already seen!

**Comment by flannery-denny** [comment]
@schanzer Do you think this would add something as optional reading?

https://www.nyclu.org/en/press-releases/court-orders-nypd-produce-stop-and-frisk-database-nyclu

**Comment by flannery-denny** [comment]
Note for FD: One other idea that I just remembered was to add something that highlighted how diverse teams generate better survey questions / more complete lists of options to choose from.

**Comment by flannery-denny** [comment]
@schanzer clarifying that the most uptodate version is on fall2022-flex

**Comment by schanzer** [comment]
@flannery-denny ah! Since that branch is just for the flex feature, next time please make sure not to push any other commits that aren't directly related to the flex stuff.

Now that I'm seeing the edits, it definitely looks even better. I fixed survey-analysis.adoc using a mechanism I hate (the same reason it's not as easy as I'd hoped to fix the whats-on-your-mind pages). I don't think the NYPD article is super-relevant to this lesson the way that, say, the NYTimes article, is.

Once the rubric is done I think this is good to go!

**Comment by flannery-denny** [comment]
@schanzer closing because what's left is issue #865.
