### ISSUE TITLE
Make master PD Decks - Save them in Workshop Folder on GDrive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#873]
- [ ] Create a PD Supplement Slides Deck of content that doesn’t belong in lesson plans and should come at the beginning and end ... things like differentiating for ELL, challenging teachers understanding of Circle of Evaluation (from algebra pd), what i s bootstrap

- [ ] One Algebra Deck (3 days) 

- [ ] One DS Deck (4 days) - NYC fall 2021

- [ ] One Crossover Deck (5 days) - Oklahoma fall 2021

**Comment by flannery-denny** [comment]
@schanzer please share links to daily exit surveys

**Comment by flannery-denny** [comment]
@schanzer This slides should be updated to include all current algebra lessons. Right? Also, I'm not following the color scheme logic. What should the legend be
![Screen Shot 2022-06-15 at 10 17 31 AM](https://user-images.githubusercontent.com/66691020/173864253-e11cd8b3-12f3-438f-8e2e-ca8faf00adae.png)

**Comment by flannery-denny** [comment]
@schanzer Is there a good reason not to mention that lessons are aligned with CS Standards on this slide?
![Screen Shot 2022-06-15 at 10 24 53 AM](https://user-images.githubusercontent.com/66691020/173865638-1a6ce01a-6c48-4f90-95c6-daca835d4a15.png)

**Comment by flannery-denny** [comment]
@schanzer Please lmk if this 5-day outline is ready for slide decking when you get a chance. [https://docs.google.com/document/d/18EIIP-mpnbK8oU3cJD4tWmDBjde0LSPrsDGZnilE08M/edit?usp=sharing](https://docs.google.com/document/d/18EIIP-mpnbK8oU3cJD4tWmDBjde0LSPrsDGZnilE08M/edit?usp=sharing)

**Comment by schanzer** [comment]
@flannery-denny Thanks! I left a few comments. Let me know what you think?

**Comment by flannery-denny** [comment]
@schanzer I've made it as far as the defining values lesson and we still haven't asked teachers to save a copy of a single starter file, which means that they don't know how to do it if they wanted to. At what point do we want to have them start saving copies? Adding a checkbox to the top to make sure we audit all PD slide decks to decide whether starter files should be embedded or copies should be saved.

**Comment by flannery-denny** [comment]
@schanzer question re: embedding.
on Day 3 I'm seeing rocket-height embedded on slides 16-18. They're supposed to save a copy on slide 16. I'm not 100% sure about how embedding works, but I'm guessing that we 

1. probably shouldn't embed files at all if we're having them save a copy of them?
2. if we're embedding, we need to remind them to save before advancing to the next slide?
3. if we're embedding something after the first time a file appears, we should embed the editor rather than the original file or they won't see their changes? 

Please let me know.

**Comment by flannery-denny** [comment]
@retabak I'm seeing a lot of slides where we are directing students to open a saved copy of a starter file.

If we're embedding anything on slides like these, we should be embedding code.pyret.org/editor so that they can access their saved files. We should not be embedding blank starter files after they've already been directed to save a copy of them. (providing links for those who didn't save is useful, however)

**Comment by schanzer** [comment]
@flannery-denny 

1. Think about running a virtual training using these materials. The lesson asks people to first _experiment with the unmodified rocket-height file_, before editing it themselves. Embedding it in PearDeck and then having them save it later allows for exactly this use-case.
2. No saving necessary
3. I don't understand how embedding a blank editor will help them see their changes. Is that what you're proposing, or have I misunderstood?

**Comment by flannery-denny** [comment]
I am suggesting that the directions don't make sense and I'd like to know how you want them fixed.

Slide 16:

> Open the [Rocket Height Starter File](https://code.pyret.org/editor#share=1Wvu39Uf0vmlA6s2HO5nOmGm-PtnTvfCf) in a new tab, and Save/Remix a copy of your own.
> Read the code before you click Run.
> What do you Notice? What do you Wonder?

Slide 17: 

> Click Run to see the simulation start running on your computer.
> What happens when you press the spacebar?
> What were you expecting to happen?
> What happens when you press b?
> Is rocket-height working?
> Close the window with the rocket, so you can see the code.
> 

Slide 18:

> Let's investigate why we weren't alerted to the problem when the computer checked the function definition against the examples.
> Type rocket-height(0) into the interactions area.
> What happens when we give the rocket-height function an input of 0?
> Is that what we want it to do?
> What happens when we give the rocket-height function an input of 10?
> Is that what we want it to do?
> Why did the examples pass?
> 

slide 22:

> Once you've completed the Design Recipe page for rocket-height, type the code into the definitions area, replacing any missing and incorrect code with your own.
> Be sure to add the contract, purpose statement, and examples.
> Save your work when you're done!

(This slide has not link to anything! Definitely a problem if they've closed a window...)

If we told them to open the file in a new tab, it's confusing to continue to embed a starter file in the slides. 
I was thinking that if we embed the editor instead of the starter file, they are poised to navigate to their own file?
Perhaps we should we embed and not tell them to save until slide 22.

**Comment by schanzer** [comment]
> Perhaps we should we embed and not tell them to save until slide 22.
@flannery-denny I like this proposal a lot.

**Comment by flannery-denny** [comment]
@schanzer I am surprised to see where did you get that back in the collaboration slides. We took it out of this lesson because it didn't fit the title "problem solving together" and you were going to figure out where else to put it...

**Comment by schanzer** [comment]
@flannery-denny Sorry, what content are you referring to?

**Comment by flannery-denny** [comment]
@schanzer I just noticed that for Day 3 the slides for design recipe telephone were made so that you could click on the problem sets... but this activity is dependent upon printing the problems! I've deleted them from the master PD deck and made a note about printing them ahead of time on the schedule.

Also, you included them in both the day 3 and day 4 deck. I fixed that in master and alabama.

Player animation was in the master pd deck twice. Fixed that for Alabama, too.

**Comment by flannery-denny** [comment]
@schanzer I think the 3-day pd slides are done. Please confirm that the way that day 3 player animation gives away the piecewise function is what you had in mind.

re: your question about the content I was referring to, **where did you get that** is appearing in the pd slide deck directly following the dr telephone.

**Comment by flannery-denny** [comment]
@schanzer 

- [ ] this issue lists a 5-day crossover deck. Pretty sure you made that already? true?
- [ ]  Would you like me to work on condensing it? If so, where would I find it?
- [ ] the algebra pd deck folder suggests that we might want a 4-day version. It's not listed on this issue. Confirming we have a pd scheduled to use it and it should be added to this issue?

**Comment by schanzer** [comment]
@flannery-denny I have not made the 5-day crossover deck. The 5-day algebra one had a hard deadline, which is why I needed to take on the last 3 days. The rest of the issue is still in your wheelhouse.

Good question re:4-day algebra. I think we should punt on it for now, as we don't have any summer PDs that require it.

**Comment by flannery-denny** [comment]
@schanzer Here's my proposal for the crossover deck [https://docs.google.com/document/d/1jEm7ZHW1tMnT9iZwuwsF_5C9YJQt4N1O4r42HXMrq58/edit?usp=sharing](https://docs.google.com/document/d/1jEm7ZHW1tMnT9iZwuwsF_5C9YJQt4N1O4r42HXMrq58/edit?usp=sharing)
I know that you had suggested the we use OK as a model, but I think it's way more fun to make a game! And if we are already running pds that do that in 3 days, it leaves 2 days for DS... If you're able to weigh in this evening, I'll get to work on making it happen tomorrow.

**Comment by schanzer** [comment]
@flannery-denny Making a game in 3 days _is_ possible, but it's definitely a stretch! I can definitely say that there's no way there will be time for any DS on day 3. Personally I'd suggest removing the game and giving flags top-billing: teachers love it, and it's a great exercise in function composition.

But if you want to keep the game, I understand. However, I would strongly urge you to spread that content out over 3.5 days, then do a very thin intro to DS. I would NOT teach defining table functions, or methods.

**Comment by flannery-denny** [comment]
@schanzer Do we have different end of course surveys for algebra and data science? if so, do we need to make a new one for the crossover workshop?

**Comment by flannery-denny** [comment]
@schanzer I've slimmed the algebra slides, but barely did any slimming for the DS slides, because it looks like you didn't do any slimming for the decks in the pd you're running. If your experience with this week's pd leads you to think ds could be slimmed more, lmk and I can give it more attention. The remaining to dos on this issue are in your wheelhouse. close when you see fit.

**Comment by schanzer** [comment]
@flannery-denny teachers should start saving files when they are working in the definitions area. Defining values is probably the first place where this happens, so that's the right place to do it.

**Comment by schanzer** [comment]
Survey has been completed. Thanks for all your work on this! Closing.
