### ISSUE TITLE
Update textbook alignments

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#876]
Make sure these are updated to reflect new/changed lessons

**Comment by flannery-denny** [comment]
@schanzer What is the appropriate format for linking to a lesson? This isn't working. [@link{https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/lessons/function-composition/index.shtml](@link{https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/lessons/function-composition/index.shtml)

I have updated the names of all of the lesson titles that were obsolete.

- cmp alignments did not link to lessons.
- IM alignments all linked to broken / old files.

**Comment by flannery-denny** [comment]
@schanzer @ds26gte I have been trying to solve the puzzle of the broken links in the textbook alignment pages and I think I have uncovered the problem. 

- The pages are stored within a pathway. 
- The pathways are language specific.
- The pages are NOT pathway specific. They link to DS pages and Algebra pages. So, when I build a pathway, not all of the links build... I will push as good of a fix as I can shortly, but I am not convinced that there is a way to build these pages correctly as long as they are stored within a pathway.

**Comment by flannery-denny** [comment]
@schanzer Not sure why, but some of the links on these pages have large font and some have small. Perhaps this relates to the float issue you're working to resolve? This image is from cmp6
![Screen Shot 2022-08-02 at 5 18 57 AM](https://user-images.githubusercontent.com/66691020/182351989-170b9624-d4b3-4e79-a1d0-b3d08a83df61.png)
?

**Comment by flannery-denny** [comment]
@schanzer other than the link sizes being inconsistent, all issues have been resolved. Close when completed

It would take a very different amount of work to think about whether any of the new lessons made this year align with IM and CMP, identify images for those lessons and describe those lessons in language that connects back to the IM/CMP lessons. If you think that is a priority, I suggest we make a separate issue with a list of all of the new lessons from 2022 and checkboxes for each of the 7 IM/CMP courses that Rachel and I would have to think through.

**Comment by schanzer** [comment]
@flannery-denny thanks for working on this. The links are related to the post-processing @ds26gte is doing to work around the image-caption bug, which we still need to track down. (@ds26gte , can you turn off the post-processing until this bug is resolved? Now we're getting bug reports related to the workaround for the existing bug, which is only adding to the complexity).

Please use season/year links when linking to content in the same release, instead of 'latest'. "Latest" links to any specific lessons will break as soon as we change the title of those lessons or remove them in the future, and these alignment documents are updated on a per seasons/year basis.

Making a new issue is totally reasonable. Once that's done feel free to close this one.

**Comment by schanzer** [comment]
@ds26gte would it not make sense to have these textbook pages stored in `shared`? I know you've suggested making them lessons in the past, but that feels even more morally wrong to me than making the projects into lessons.

**Comment by flannery-denny** [comment]
@schanzer I think that if you'd done the alignments yourself, you would be proponenting latest. 

It took me minutes to switch 
- spread of a dataset -> box plots
- linear relationships -> functions can be linear
- defining linear relationships -> defining linear functions

Updating and testing every single link in every file took hours. Particularly because there were many link formats and some of them were pathway specific, which these files cross.

I think making it easy to maintain new alignment pages is more important than old ones, in that those textbooks will also get updated and have their lesson names change.

If you still want me to go back and change every link, please include exactly what the link format should look like in your next comment so that I can copy it.

Working on this also made me wonder what happened to you using the broken link tester as part of the protocol before pushing a new release. It would still be worth testing our website for broken links at this point.

**Comment by schanzer** [comment]
@flannery-denny of course I used the broken link tester. We've known for months that these links were broken, which is why we created this issue. The tester can only confirm that the links are broken - it doesn't fix them.

Why were you spending hours testing the links by hand? That's what the tester is for.

"Latest" is a surefire way to get broken links. Think about all the lessons we changed or renamed this year alone! 

Given that these pages are year/season specific, it's probably even better to do *relative* links instead of absolute ones. That way we can dispense with the issue entirely. I'll make this change shortly.

**Comment by flannery-denny** [comment]
@schanzer It's hard to use a tool that I've never been taught to use. It would be great if you could teach me and @retabak how to use the broken link tester.

Fine with me if you want to change all of the links every year. As far as I know, we only changed 3 lesson titles this year... and I don't think we changed any the previous year. 

If it will only take you moments to change the links, that's great news... and it's confusing why it didn't happen sooner. Maybe you have some other tools in your toolbox for this job that I don't know about and could teach me those, too? 

For me, this job involves a lot of close reading of asciidocs, making mistakes, catching them, and fixing them.
